#!/usr/bin/env ruby

require 'open-uri'
require 'minitar'
require 'zlib'

default =    URI.open('https://github.com/postmodern/ruby-install/releases').read.match(/v(\d+\.\d+\.\d+)/).to_a[1].to_s
version =    ARGV[0] || default
uri =        "https://github.com/postmodern/ruby-install/archive/v#{version}.tar.gz"
src_prefix = '/tmp/ruby-install_install'
cmd        = "cd #{src_prefix}/ruby-install-#{version} && sudo make install && rm -Rf #{src_prefix};\\\n" +
             "test -f /etc/redhat-release && (rpm --quiet -q bzip2 || sudo yum -y install bzip2)"

puts "Download from #{uri}"
Minitar.unpack(Zlib::GzipReader.new(URI.open(uri,"rb")), src_prefix)
puts cmd
puts `#{cmd}`

